### ISSUE TITLE
Error compiling with only tcp feature enabled

### ISSUE THREAD

**Issue by pbellchambers** [lemunozm/message-io#151]
Since version 0.15.0 I get the below error when compiling if I have only the tcp feature enabled.

In my cargo.toml:
`message-io = { version = "0.15.0", default-features = false, features = ["tcp"] }`

Error on cargo build:
```
   Compiling message-io v0.15.0                                                                                                                                                                                                                                                                                        
error[E0432]: unresolved import `socket2`                                                                                                                                                                                                                                                                              
  --> C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\message-io-0.15.0\src\adapters\tcp.rs:10:5
   |
10 | use socket2::{Socket, TcpKeepalive};
   |     ^^^^^^^ use of undeclared crate or module `socket2`

error[E0432]: unresolved import `socket2`
  --> C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\message-io-0.15.0\src\adapters\framed_tcp.rs:11:5
   |
11 | use socket2::{Socket, TcpKeepalive};
   |     ^^^^^^^ use of undeclared crate or module `socket2`

For more information about this error, try `rustc --explain E0432`.                                                                                                                                                                                                                                                    
error: could not compile `message-io` due to 2 previous errors
```

This worked ok in `0.14.8`, and it works ok if `features = ["tcp", "udp"]`, just not with tcp alone.

**Comment by sigmaSd** [comment]
https://github.com/lemunozm/message-io/pull/143 added a dep on socket2 for tcp, but didn't update Cargo.toml features accordingly

**Comment by lemunozm** [comment]
Thanks for your search @sigmaSd! Very appreciated.

Fix here: https://github.com/lemunozm/message-io/pull/152

**Comment by lemunozm** [comment]
The new release containing the fix: `v0.15.1`
